#!/bin/bash
#
# Build a direct-distribution .app + zip for Nani.
# Distribution: nani.app — no App Store, no Developer ID, no notarization.
#
# First-launch UX: users will see "Nani can't be opened because Apple cannot
# check it for malicious software." Tell them to right-click the app and
# choose Open (or run `xattr -d com.apple.quarantine /Applications/Nani.app`).
# Document this clearly on the download page.
#
# Updates are still secure: Sparkle verifies them with an EdDSA signature
# (free, generated by `generate_keys` from Sparkle). Put your public key in
# Info.plist as SUPublicEDKey when you're ready to ship updates.
#
set -e

APP_NAME="Nani"
VERSION="1.0.0"
BUILD_DIR=".build/apple/Products/Release"
APP_BUNDLE="Release/$APP_NAME.app"
ZIP_PATH="Release/${APP_NAME}_${VERSION}.zip"

echo "🚀 Building $APP_NAME $VERSION (universal arm64 + x86_64)"
swift build -c release --arch arm64 --arch x86_64

# Regenerate the app icon from app-icon.png so distribution always ships
# the latest source. Cheap (~1s) and keeps the .icns reproducible.
if [ -f "app-icon.png" ]; then
    echo "🎨 Generating AppIcon.icns"
    swift Scripts/make_icon.swift app-icon.png AppIcon.icns > /dev/null
fi

echo "📦 Assembling .app bundle"
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"
mkdir -p "$APP_BUNDLE/Contents/Frameworks"

cp "$BUILD_DIR/$APP_NAME" "$APP_BUNDLE/Contents/MacOS/"

if [ ! -f "Info.plist" ]; then
    echo "❌ Info.plist missing at repo root"
    exit 1
fi
cp Info.plist "$APP_BUNDLE/Contents/Info.plist"

if [ -f "AppIcon.icns" ]; then
    cp AppIcon.icns "$APP_BUNDLE/Contents/Resources/"
fi

# Bundled SPM resources (Bundle.module expects "<Module>_<Module>.bundle")
if [ -d "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle" ]; then
    cp -R "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle" "$APP_BUNDLE/Contents/Resources/"
fi

# Sparkle framework + rpath
if [ -d "$BUILD_DIR/Sparkle.framework" ]; then
    cp -R "$BUILD_DIR/Sparkle.framework" "$APP_BUNDLE/Contents/Frameworks/"
    install_name_tool -add_rpath @executable_path/../Frameworks \
        "$APP_BUNDLE/Contents/MacOS/$APP_NAME"
fi

# Ad-hoc sign so the binary launches on Apple Silicon. No certificate
# required — `-s -` is the built-in ad-hoc identity.
echo "🔏 Ad-hoc signing (no cert needed)"
codesign --force --deep --sign - "$APP_BUNDLE"

# Zip for upload to the website.
echo "📦 Zipping → $ZIP_PATH"
rm -f "$ZIP_PATH"
ditto -c -k --keepParent "$APP_BUNDLE" "$ZIP_PATH"

echo "✅ Done. Upload: $ZIP_PATH"
