    static let builtInSounds: [SoundAsset] = [
        SoundAsset(id: "among_us_round_start", name: "Among Us Round Start", fileName: "among_us_round_start", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "anime_ahh", name: "Anime Ahh", fileName: "anime_ahh", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "anime_girl_senpai", name: "Anime Girl Senpai", fileName: "anime_girl_senpai", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "anime_girl_voice", name: "Anime Girl Voice", fileName: "anime_girl_voice", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "nani", name: "Anime Wow", fileName: "anime_wow", fileExtension: "mp3", duration: 0.8, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "avocados_from_mexico", name: "Avocados From Mexico", fileName: "avocados_from_mexico", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "awkward_moment", name: "Awkward Moment", fileName: "awkward_moment", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "brook_laugh", name: "Brook Laugh", fileName: "brook_laugh", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "caught_a_pokemon", name: "Caught A Pokemon", fileName: "caught_a_pokemon", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "death_note_writing", name: "Death Note Writing", fileName: "death_note_writing", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "discord_mute", name: "Discord Mute", fileName: "discord_mute", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "e_girl_stop", name: "E Girl Stop", fileName: "e_girl_stop", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "wow", name: "Ehhh Cute", fileName: "ehhh_cute_anime", fileExtension: "mp3", duration: 0.6, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "yatta", name: "Gambare", fileName: "gambare_gambare", fileExtension: "mp3", duration: 0.7, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "gold_ship_scream", name: "Gold Ship Scream", fileName: "gold_ship_scream", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "hello_trailer", name: "Hello Trailer", fileName: "hello_trailer", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "hollow_purple", name: "Hollow Purple", fileName: "hollow_purple", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "i_am_atomic", name: "I Am Atomic", fileName: "i_am_atomic", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "im_spongebob", name: "Im Spongebob", fileName: "im_spongebob", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "kamehameha_charge", name: "Kamehameha Charge", fileName: "kamehameha_charge", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "kuru_kuru", name: "Kuru Kuru", fileName: "kuru_kuru", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "light_yagami_is_sus", name: "Light Yagami Is Sus", fileName: "light_yagami_is_sus", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "lightning_strike", name: "Lightning Strike", fileName: "lightning_strike", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "mordecai_coffee", name: "Mordecai Coffee", fileName: "mordecai_coffee", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "myanee_ohayou", name: "Myanee Ohayou", fileName: "myanee_ohayou", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "one_piece_ringtone", name: "One Piece Ringtone", fileName: "one_piece_ringtone", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "perry_platypus_growl", name: "Perry Platypus Growl", fileName: "perry_platypus_growl", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "random_effect", name: "Random Effect", fileName: "random_effect", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "return_by_death", name: "Return By Death", fileName: "return_by_death", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "ryu_sweet", name: "Ryu Sweet", fileName: "ryu_sweet", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "sanctuary_guardian", name: "Sanctuary Guardian", fileName: "sanctuary_guardian", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "screen_record_clip", name: "Screen Record Clip", fileName: "screen_record_clip", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "sound_effect_20_2", name: "Sound Effect 20 2", fileName: "sound_effect_20_2", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "spongebob_disappointed", name: "Spongebob Disappointed", fileName: "spongebob_disappointed", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "tuturu", name: "Tuturu!", fileName: "tuturu", fileExtension: "mp3", duration: 0.9, isBuiltIn: true, category: .greeting),
        SoundAsset(id: "tuturu_alternate", name: "Tuturu Alternate", fileName: "tuturu_alternate", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "ultra_instinct", name: "Ultra Instinct", fileName: "ultra_instinct", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "very_angry_goku", name: "Very Angry Goku", fileName: "very_angry_goku", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "wow_cute_anime", name: "Wow Cute Anime", fileName: "wow_cute_anime", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "ara_ara", name: "Yamete Kudasai", fileName: "yamete_kudasai", fileExtension: "mp3", duration: 1.2, isBuiltIn: true, category: .reaction),
        SoundAsset(id: "yandere_laugh", name: "Yandere Laugh", fileName: "yandere_laugh", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "yes_yes_yes", name: "Yes Yes Yes", fileName: "yes_yes_yes", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "yowai_mo", name: "Yowai Mo", fileName: "yowai_mo", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation),
        SoundAsset(id: "yuta_louder", name: "Yuta Louder", fileName: "yuta_louder", fileExtension: "mp3", duration: 1.0, isBuiltIn: true, category: .exclamation)
    ]
